### ISSUE TITLE
tiovxisp: Wrong blocksize input will give SIGSEGV

### ISSUE THREAD

**Issue by dchvs** [TexasInstruments/edgeai-gst-plugins#134]
The following pipeline does perform a wrong blocksize calculation for the given caps, and triggers a segment violation signal.

The blocksize formula it's the following:
```bash
blocksize = bpp * w * h
``` 
In this case, the bit per pixel (BPP)  for BGGR16 should equals to 2 refering to bytes that type uses. Anyway, in general terms, blocksizes other that the right one will trigger this issue.

```bash
root@j7-2:~# GST_DEBUG=tiovxsimo:4,tiovxisp:4 gst-launch-1.0  filesrc location=/dev/zero blocksize=$((1*320*240)) ! \
video/x-bayer,format=bggr16,width=320,height=240 ! \
tiovxisp sensor-name="SENSOR_SONY_IMX390_UB953_D3" \
dcc-isp-file=/dev/zero dcc-2a-file=/opt/imaging/imx390/dcc_2a.bin format-msb=11 ! video/x-raw ! fakesink
APP: Init ... !!!
MEM: Init ... !!!
MEM: Initialized DMA HEAP (fd=4) !!!
MEM: Init ... Done !!!
IPC: Init ... !!!
IPC: Init ... Done !!!
REMOTE_SERVICE: Init ... !!!
REMOTE_SERVICE: Init ... Done !!!
  1866.166924 s: GTC Frequency = 200 MHz
APP: Init ... Done !!!
  1866.167268 s:  VX_ZONE_INIT:Enabled
  1866.167362 s:  VX_ZONE_ERROR:Enabled
  1866.167527 s:  VX_ZONE_WARNING:Enabled
  1866.168261 s:  VX_ZONE_INIT:[tivxInitLocal:111] Initialization Done !!!
  1866.168602 s:  VX_ZONE_INIT:[tivxHostInitLocal:86] Initialization Done for HOST !!!
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Caught SIGSEGV
New clock: GstSystemClock
#0  0x0000ffffbcbd233c in poll () from /lib/libc.so.6
#1  0x0000ffffbcd6f7e0 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x0000ffffbcd6fc38 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#3  0x0000ffffbceb0634 in gst_bus_poll () from /usr/lib/libgstreamer-1.0.so.0
#4  0x0000000000404988 in _start ()
Spinning.  Please run 'gdb gst-launch-1.0 1601' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
```

**Comment by dchvs** [comment]
Fixed by [PR#147: Exit plugin execution gently when blocksize from upstream is invalid](https://github.com/TexasInstruments/edgeai-gst-plugins/pull/147)
